server:
  address: 0.0.0.0
  port: ${PORT}
  servlet:
    session:
      cookie:
        same-site: strict

spring:
  application:
    name: VietBus
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      url: ${REDIS_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  main:
    web-application-type: servlet
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: ${QUARTZ_THREAD_COUNT}

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

momo:
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  api-url: https://test-payment.momo.vn/v2/gateway/api/create
  redirect-url: https://your-domain.com/api/payment/momo/return
  ipn-url: https://capital-operating-smashup.ngrok-free.dev/api/v1/app/webhook/momo

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  api-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: https://capital-operating-smashup.ngrok-free.dev/api/payment/vnpay/return
  ipn-url: https://capital-operating-smashup.ngrok-free.dev/api/v1/app/webhook/vnpay
  version: "2.1.0"
  command: pay
  currency-code: VND
  locale: vn