server:
  address: 0.0.0.0 # Other device can connect
  port: 8088

spring:
  application:
    name: VietBus
  datasource:
    url: jdbc:postgresql://localhost:5432/VietBusDB
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    web-application-type: servlet
  mail:
    host: smtp.gmail.com
    port: 587
    username: tuannhat226@gmail.com
    password: ofkh vfej yttv zupv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: mX4r9FQ+Z8nZ0Y8bW+1E8g4b7v7pZbM+KcZl0YJm8mM=
  expiration: 86400000 # 1 ngày (ms)
